"""Real HTTP -> real SQLite reads against a real generated demo batch --
these endpoints have no daemon dependency at all (pure reads), which is
itself part of what's being verified.
"""
from __future__ import annotations

import pytest
from httpx import AsyncClient

from krauken.daemon.app import Daemon
from krauken.db.seed import seed_demo_batch


@pytest.fixture
def seeded(daemon: Daemon):
    seed_demo_batch(daemon.ctx.db_path)


async def test_list_fermentations_includes_the_demo_batch(client: AsyncClient, seeded):
    resp = await client.get("/api/v1/fermentations")
    assert resp.status_code == 200
    items = resp.json()
    assert len(items) == 1
    item = items[0]
    assert item["name"] == "Sample batch - Citra Pale Ale"
    assert item["demo"] is True
    assert item["simulated"] is True
    assert item["status"] == "completed"
    assert item["yeast_name"] == "SafAle US-05 - American ale"
    assert item["abv_pct"] is not None and item["abv_pct"] > 0


async def test_list_fermentations_filters_by_status(client: AsyncClient, seeded):
    resp = await client.get("/api/v1/fermentations", params={"status": "active"})
    assert resp.json() == []


async def test_get_fermentation_detail_includes_all_five_stages(client: AsyncClient, seeded):
    list_resp = await client.get("/api/v1/fermentations")
    fermentation_id = list_resp.json()[0]["id"]

    resp = await client.get(f"/api/v1/fermentations/{fermentation_id}")
    assert resp.status_code == 200
    body = resp.json()
    assert len(body["stages"]) == 5
    assert [s["stage_type"] for s in body["stages"]] == [
        "primary", "free_rise", "diacetyl_rest", "conditioning", "cold_crash",
    ]


async def test_get_fermentation_detail_404_for_unknown_id(client: AsyncClient, seeded):
    resp = await client.get("/api/v1/fermentations/99999")
    assert resp.status_code == 404


async def test_series_is_columnar_and_has_duty_and_no_gaps(client: AsyncClient, seeded):
    list_resp = await client.get("/api/v1/fermentations")
    fermentation_id = list_resp.json()[0]["id"]

    resp = await client.get(f"/api/v1/fermentations/{fermentation_id}/series")
    assert resp.status_code == 200
    body = resp.json()
    assert body["point_count"] > 500
    assert len(body["ts"]) == body["point_count"]
    assert len(body["beer_temp_f"]) == body["point_count"]
    # Duty cycle must sum close to 100% (idle isn't separately zero-filled
    # for rounding, so allow a hair of slack).
    duty = body["duty"]
    assert 99.0 <= duty["cool_pct"] + duty["heat_pct"] + duty["idle_pct"] <= 100.5
    # The demo batch is generated by one continuous, uninterrupted run --
    # it must have no gaps at all (the sampler's own heartbeat guarantees this).
    assert body["gaps"] == []


async def test_series_for_unknown_fermentation_is_empty_not_an_error(client: AsyncClient, seeded):
    resp = await client.get("/api/v1/fermentations/99999/series")
    assert resp.status_code == 200
    assert resp.json()["point_count"] == 0
